# Stage 1: Build the collector binary from pre-generated source.
# Source in cmd/otelcol-lightspeed/ is generated by OCB (make generate)
# and committed to the repo for hermetic CI builds.
FROM registry.redhat.io/ubi9/go-toolset:9.8-1780490420 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

# Cache module downloads — copy go.mod/go.sum first so source changes
# don't invalidate the download layer.
COPY cmd/otelcol-lightspeed/go.mod cmd/otelcol-lightspeed/go.sum cmd/otelcol-lightspeed/
COPY postgresexporter/go.mod postgresexporter/go.sum postgresexporter/
COPY extension/postgresadmin/go.mod extension/postgresadmin/go.sum extension/postgresadmin/
COPY extension/httpsmetrics/go.mod extension/httpsmetrics/go.sum extension/httpsmetrics/
RUN cd cmd/otelcol-lightspeed && go mod download

# Copy source.
COPY cmd/otelcol-lightspeed/ cmd/otelcol-lightspeed/
COPY postgresexporter/ postgresexporter/
COPY extension/ extension/

USER root

RUN cd cmd/otelcol-lightspeed && \
    CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -trimpath -o /workspace/otelcol-lightspeed .


# Stage 2: Minimal runtime image.
FROM registry.redhat.io/ubi9/ubi-minimal:9.8-1782366411

WORKDIR /

COPY --from=builder /workspace/otelcol-lightspeed .

# Red Hat certification requires LICENSE under /licenses/.
RUN mkdir /licenses
COPY LICENSE /licenses/.

LABEL name="openshift-lightspeed/otelcol-lightspeed" \
      summary="Custom OpenTelemetry Collector for OpenShift Lightspeed" \
      description="Receives OTLP telemetry and writes logs directly to PostgreSQL." \
      io.k8s.display-name="OTel Collector — Lightspeed" \
      io.k8s.description="Custom OpenTelemetry Collector distribution that exports logs to PostgreSQL." \
      io.openshift.tags="opentelemetry,otel,collector,postgres,logs"

# OTLP gRPC/HTTP, health check, admin API, and metrics ports.
EXPOSE 4317 4318 8080 8888 13133

# Run as non-root, same UID as lightspeed-operator.
USER 65532:65532

ENTRYPOINT ["/otelcol-lightspeed"]
